### ISSUE TITLE
[Bug] Widget does not fully initialize if wallet not unlocked when plasmashell starts.

### ISSUE THREAD

**Issue by AlekEagle** [korapp/plasma-homeassistant#15]
**Describe the bug**
If your KDE Wallet does not unlock at login when plasmashell starts and loads the widget, the widget will display "Configure" until plasmashell is restarted. e.g. `plasmashell --replace` in Krunner.

**To Reproduce**
1. Configure your default wallet to require user interaction in order to unlock (e.g. PGP Encryption with a physical GPG key)
2. Login to your user account.
3. Unlock your default KDE wallet.

**Expected behavior**
Once the wallet is unlocked, the widget will be able to obtain the access token for Home Assistant, authenticate, and display the entities configured to be displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - Distribution: KDE neon 5.27
 - KDE Plasma 5.27.10
 - KDE Frameworks 5.113.0
 - Qt 5.15.11

**Additional context**
I have not tried using classic blowfish encryption with a password.

**Comment by korapp** [comment]
Quite a find, thanks for reporting.
