### ISSUE TITLE
QWebSocketPrivate::processHandshake: Unhandled http status code: 404 (Not Found).

### ISSUE THREAD

**Issue by CleanShirtUK** [korapp/plasma-homeassistant#18]
**Describe the bug**
After installation, I created a token on my HA instance and input the details. When attempting to load, I get a spinning cog on the 'items' menu and nothing loads, as well as the following error on a banner: QWebSocketPrivate::processHandshake: Unhandled http status code: 404 (Not Found).

**To Reproduce**
1. Install the plasmoid through 'Get new plugins'
2. input the required information

**Expected behavior**
The plasmoid to get information from my HA instance

**Desktop (please complete the following information):**
Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.7.0-zen3-1-zen (64-bit)
Graphics Platform: Wayland

**Additional context**
I'm sure I'm missing something _painfully_ obvious. I can access HA by posting the same URL in a browser without issue.

**Comment by korapp** [comment]
Does visiting `[your_ha_ur]/api/` also return a 404? (Trailing slash is important)

**Comment by CleanShirtUK** [comment]
Visiting http://[SERVER-IP]:8123/api/ results in 401: Unauthorized... So I'm assuming that means I'm barking up the wrong tree right, and something in my HA setup?

**Comment by NWAF-NAN00K** [comment]
I was getting the same error when I used the url of homeassistant with a trailing slash at the end, ie http://homeassistant.local:8123/. With traling slash You can see wrong profile url in applet config: http://homeassistant:8123//profile. Without the trailing slash, the applet connected to homeassistant without errors. However, I also created a special - non admin user for the plasma applet.

However, the applet behaves strangely when entering the url. When the traling slash is deleted from existing url, the apply button not became active. The applet does not take this as a "change".

**Comment by D3SOX** [comment]
I think I have the same issue 

> Is it possible that you don't have a `default_config:` or at least `frontend:` entry in the server configuration?

I don't think so

![image](https://github.com/korapp/plasma-homeassistant/assets/24937357/3a6777f1-3c28-415e-b6cc-95b8ec6eb26c)

**Comment by korapp** [comment]
Can you see HomeAssistant entry in kwalletmanager?
