### ISSUE TITLE
Add User Agent so access logs do not look suspicious on failed auth attempts.

### ISSUE THREAD

**Issue by AlekEagle** [korapp/plasma-homeassistant#19]
Self explanatory, just spent about an hour looking into network logs and even wiresharking my network to pinpoint the source of traffic (spoiler alert: it was my computer failing to get credentials again! (No I don't think I updated the widget yet))

**Comment by korapp** [comment]
Unfortunately, I don't think this is doable in QML Websocket.
Even if it were, I don't know if it would be of much benefit, as you should be able to see your hostname and IP address directly in the server logs in the event of a failed login.

**Comment by AlekEagle** [comment]
Fair enough, and you're probably right about the hostname thing, but I decided to use my external access URL instead of my internal URL, and led me to believe it was an external threat trying to access my network. If that isn't doable then don't worry about it, thank you for the really nice plasma widget though!
