### ISSUE TITLE
module "QtWebSockets" is not installed

### ISSUE THREAD

**Issue by jvw1954** [korapp/plasma-homeassistant#2]
On GNU/Debian 12 - Bookworm I get the following message.

_file:///home/jaap/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/main.qml:29:5: Type WsClient unavailable

file:///home/jaap/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/WsClient.qml:2:1: module "QtWebSockets" is not installed_

libqt5websockets5. libqt5websockets6. qml-module-qt-websockets, qml-module-qtwebsockets, qml6-module-qtwebsockets are installed.

Plasma-homeassistant is installed with plasma widgets installer.

**Comment by korapp** [comment]
Did you relogin or restart plasma (`plasmashell --replace`) after installing qml-module-qtwebsockets?
Plasma may not be able to load the library at runtime if you have just installed it.

**Comment by rnqlover** [comment]
> 

Have the same issue On Debian 12. Your advice help me, thx
`sudo apt-get install qml-module-qtwebsockets
`
Then Alt+F2
`plasmashell --replace`
or reboot

**Comment by korapp** [comment]
Thank you for your comment. I will add the relevant information to the description as the problem turns out to be more common.

**Comment by PDXUser** [comment]
I have the same issue with Arch Linux, I installed both and still not working, rebooted after doing this.  
file:///home/PDXUser/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/main.qml:29:5: Type WsClient unavailable

file:///home/PDXuser/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/WsClient.qml:2:1: module "QtWebSockets" is not installed

Below is what I show for being installed for both: 

1.  aur/libwsclient-git 28.d416fcb-1 (+0 0.00) (Installed)
    WebSocket client library for C.

2. extra/qt6-websockets 6.5.2-1 (96.6 KiB 364.5 KiB) [qt6] (Installed: 6.6.0beta3-1)
    Provides WebSocket communication compliant with RFC 6455

**Comment by korapp** [comment]
Try with qt5-websockets

**Comment by zabi94** [comment]
Got the same problem.
I'm on Fedora KDE, installed qt5-qtwebsockets and rebooted. Not working:

```
file:///home/user/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/main.qml:29:5: Type WsClient unavailable

file:///home/user/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/WsClient.qml:2:1: module "QtWebSockets" is not installed
```

**Comment by korapp** [comment]
Which Fedora version are use?

**Comment by zabi94** [comment]
Fedora 38 KDE spin
Plasma: 5.110.0
Qt: 5.15.10
kernel 6.5.8
Wayland

**Comment by korapp** [comment]
It looks like you need `qt5-qtwebsockets-devel` on Fedora.

**Comment by V1ck3s** [comment]
On Arch :
`sudo pacman -S qt5-websockets`
Then logout and login.
