### ISSUE TITLE
[Feature request] Plasma 6 compatibility

### ISSUE THREAD

**Issue by mynamewastaken** [korapp/plasma-homeassistant#27]
This Widget was written for an unknown older version of Plasma and is not compatible with Plasma 6.
Please contact the widget's author for an updated version.

**Comment by korapp** [comment]
It's already ported: #11.
Did you installed the [Plasma 6 version of the widget](https://www.pling.com/p/2131364/) after updating to Plasma 6?

**Comment by mynamewastaken** [comment]
Neat, thanks! No, I didn't know it was available, I only updated to Plasma 6 last night. I'll close this out.
