### ISSUE TITLE
Doesn't work on KDE6

### ISSUE THREAD

**Issue by grinco** [korapp/plasma-homeassistant#32]
Plasmoid fails to load on OpenSUSE Tumbleweed running Plasma 6

``` $ rpm -qa \*qt\*websockets\*
qt6-websockets-devel-6.6.2-1.1.x86_64
libqt5-qtwebsockets-devel-5.15.13+kde2-1.1.x86_64
```

 - Distribution: OpenSUSE Tumbleweed
 - KDE Plasma: 6.0.2
 - KDE Frameworks: 6.0.0
 - QT Version: 6.6.2

**Comment by korapp** [comment]
Could you check `qt6-websockets-imports`?
I assume KDE5 in the title is a typo.
#30

**Comment by grinco** [comment]
Thanks, i've installed wrong dependency it seems. Installing `qt6-websockets-imports` did the job.
And yes, the title was a typo. Confirming that the issue was between the keyboard and the chair.
