### ISSUE TITLE
[Feature request] Be able to change brightness or other values with a slider

### ISSUE THREAD

**Issue by jclsn** [korapp/plasma-homeassistant#34]
**Is your feature request related to a problem? Please describe.**
I can only toggle the light on and off.

**Describe the solution you'd like**
I want to control the brightness

**Comment by korapp** [comment]
Implemented:
v0.6.0 for Plasma 5
v1.2.0 for Plasma 6

**Comment by jclsn** [comment]
Nice! This work, but I think the slider is too sensitive. Can you maybe introduce some kind of smoothing?

Would also be nice to see a percentage value rather than the 8-bit integer value.
