### ISSUE TITLE
[Bug] Error after first install and use

### ISSUE THREAD

**Issue by McTom234** [korapp/plasma-homeassistant#35]
**Describe the bug**
I added the widget via KDE Discover and added the widget to my homescreen. I get this error:
```
file:///home/mctom234/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/main.qml:13:25: Type FullRepresentation unavailable

file:///home/mctom234/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/FullRepresentation.qml:66:28: Cannot assign object of type "Action" to property of type "Action_QMLTYPE_115*" as the former is neither the same as the latter nor a sub-class of it.
```

**To Reproduce**
1. Go to Discover
2. Click on freshly (first) install the plasmoid
3. Add the widget to the homescreen

**Expected behavior**
Whatever the widget should do on the first use

**Desktop (please complete the following information):**
 - Distribution: Arch 6.8.6-zen1
 - KDE Plasma 6.0.3
 - KDE Frameworks 6.1.0

**Additional context**
Maybe I am just missing some configuration steps. I am happy about every hint :smile:

**Comment by chicco-carone** [comment]
I get the same error doing the same steps but while installing the plugin from the file from the kde store directly

**Comment by korapp** [comment]
I'm not able to debug it right now, but I bet it's KDE Framework 6.1 changes.

**Comment by korapp** [comment]
Is anyone experiencing this problem on KDE Plasma 6.0.4 and KDE Frameworks 6.1.0?

**Comment by SBado** [comment]
> Is anyone experiencing this problem on KDE Plasma 6.0.4 and KDE Frameworks 6.1.0?

I am experiencing this problem on KDE Plasma 6.0.4 and KDE Frameworks 6.1.0.

```
file:///home/ste/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/main.qml:13:25: Type FullRepresentation unavailable

file:///home/ste/.local/share/plasma/plasmoids/com.github.korapp.homeassistant/contents/ui/FullRepresentation.qml:66:28: Cannot assign object of type "Action" to property of type "Action_QMLTYPE_100*" as the former is neither the same as the latter nor a sub-class of it.
```

**Comment by korapp** [comment]
No problems with other widgets or the Plasma itself?
I see that there have been [some problems with the QML cache on Arch](https://www.reddit.com/r/kde/comments/18uq79e/plasma_6_beta_2_error_loading_qml_file/), causing similar errors of mismatched types.

**Comment by SBado** [comment]
Deleting `~/.cache/plasmashell/qmlcache/` had no effect, but the fact that a fresh install of Tumbleweed was working for you (by the way, thanks for your efforts!) made me realize that maybe I just had to update my packages.
After a zypper dup it started working. Thank you!

**Comment by reidprichard** [comment]
Same issue here on OpenSUSE Tumbleweed. I keep my system up to date, with at least weekly `sudo zypper dup` and reboot, and deleting the qmlcache as described above had no effect, even after reinstalling the widget. I finally got it working with:

1. Uninstall the widget
2. `rm ~/.cache/plasmashell/qmlcache/*`
3. `sudo zypper dup`
4. Reboot
5. Reinstall the widget

Not sure what the magic sauce was, as I'd done each step in isolation several times, but there ya go.

**Comment by McTom234** [comment]
Hey @korapp, thanks for your efforts!

Unfortunately, the same error still exists on my system.

I have the following version running currently:
- Distribution: Arch 6.9.8-zen1
- KDE Plasma 6.1.2
- KDE Frameworks 6.3.0
- Qt: 6.7.2

I tried to remove the qmlcache without success.

I think I have an issue with QML on X11, but it could be a config issue as well. I haven't had time to debug this issue, it only exists on X11 tough. One comment recommended disabling the QML disk cache - I will give that a try, but since I removed the qmlcache manually, I don't have high expectations...

**Comment by korapp** [comment]
According to [this issue](https://bugs.kde.org/show_bug.cgi?id=487464), it should be fixed in Frameworks 6.4.

Until you get it, you can edit the plasmoid code locally - remove the [Action and helpfulAction property](
https://github.com/korapp/plasma-homeassistant/blob/0b266fadaea47d728867674acff6ae8fc1cc093b/package/contents/ui/FullRepresentation.qml#L66)

Its only use is to open the Readme file in case of missing libraries.

**Comment by McTom234** [comment]
Hey @korapp, thanks for your message. I installed version 6.4 and finally, everything works now! Thank you for your help and creating the widget at first!

**Comment by dgalli1** [comment]
I'm using framework 6.4, but the error seems to still be around even on this version. (Plasma 6.1.4)
