### ISSUE TITLE
Displaying only spinner, can't add entities

### ISSUE THREAD

**Issue by WallK** [korapp/plasma-homeassistant#4]
I've inputted my HA address and API key, but when I try to add entities -- they are not getting saved (or the list is displayed empty)
The widget itself is showing only a spinner

Here's couple of messages from journalctl

```
plasmashell[1250]: qml: Unsupported WebSocket scheme: file
plasmashell[1250]: qml: Messages can only be sent when the socket is open.

```

What could be causing this?
Thank you

**Comment by korapp** [comment]
There is no such information there but does the URL include the protocol and port? E.g. `http://homeassistant.lan:8123`

**Comment by WallK** [comment]
No, but I tried local domain name and ip address
Also tried with http port just to be sure

**Comment by WallK** [comment]
$ curl -fsS homeassistant.local/api/ -H "Content-Typeplication/json"
curl: (7) Failed to connect to homeassistant.local port 80: Connection refused

$ curl -fsS homeassistant.local:8123/api/ -H "Content-Typeplication/json"
curl: (22) The requested URL returned error: 401 Unauthorized

**Comment by WallK** [comment]
I did, but with ip, not domain
Widget with domain in it was still without protocol and maybe I've confused where errors came from
It works now!
Thank you for going through debugging steps with me
Maybe you should specify protocol and port requirements more prominent in the instructions?
