### ISSUE TITLE
Applet doesn't retain width or height that is less than the default across reboots in plasma 5.[Bug]

### ISSUE THREAD

**Issue by jms1989** [korapp/plasma-homeassistant#45]
**Describe the bug**
On boot up, applet doesn't retain any size that's less than the default. It will remember a size bigger than default.

**To Reproduce**
1. shrink applet window size to less than default
2. reboot
3. observe applet returns to default width or height depending on what way was shrunk.

**Expected behavior**
I expect it to remember it's dimensions across reboots.

**Desktop:**
 - Distribution: Kubuntu 24.04
 - KDE Plasma 5.27.11
 - KDE Frameworks 5.115

**Comment by korapp** [comment]
I think this may be a Plasma problem. Are you on X11 or Wayland? The latter should be more stable in this regard, AFAIK.

**Comment by jms1989** [comment]
I'm on X11 as Wayland is still too buggy for me on a nvidia gpu. I've resorted to just increasing the width to a desired size and let the height be whatever it's gonna be since I don't need any widgets below it.
