### ISSUE TITLE
[Feature request] Changing Brightness via Scroll

### ISSUE THREAD

**Issue by dgalli1** [korapp/plasma-homeassistant#52]
**Is your feature request related to a problem? Please describe.**
I can already add Switches/Lights as a Entity into the dashboard, but i select the brightness as Scroll Action it only toggles the entity.

**Describe the solution you'd like**
I would love if the brightness or other number values which are usally displayed via a slider could be modifed by scrolling up and down.

**Describe alternatives you've considered**
Might be kinda unintutive for the ui, so it would also be cool if the background could be filled with the percentage of the slider, but this seems like a lot more work.

**Comment by korapp** [comment]
Scroll Action has been implemented exactly as you describe.
Did you select the **turn_on** action and **brightness** attribute?

**Comment by dgalli1** [comment]
Ups sorry about that i think i only tried it with toggle and then gave up, after i noticed that it doesn't work.

I configured it as you told and everything worked fine.

**Comment by jclsn** [comment]
Yeah, it works. Would be nice if the sensitivity were a bit lower though. I also think it should not use 0-255, but 0-100%. I just a bit nicer for the eye.
