### ISSUE TITLE
[Bug] Not compatible with KDE Frameworks 6.6

### ISSUE THREAD

**Issue by asyd** [korapp/plasma-homeassistant#56]
**Describe the bug**
When trying the plasmoid with KDE 6.4 I have following error:

![image](https://github.com/user-attachments/assets/b1861aac-584d-4290-ac55-49db6a12707e)

**Desktop (please complete the following information):**
 - Distribution: Debian Sid
 - KDE Plasma 6.2.3
 - KDE Frameworks 6.6.0

Thanks!

**Comment by korapp** [comment]
Have you installed plasmoid for Plasma 6 https://store.kde.org/p/2131364/?

**Comment by asyd** [comment]
Oups, my bad I downloaded the version 5 indeed. Thanks and sorry for the noise!
